on: push
name:  Deploy website on push
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v4

    - name: FTP
      uses: sand4rt/ftp-deployer@v1.4
      with:
        sftp: true
        host: 109.123.232.134
        port: 2222
        username: user1
        password: ${{ secrets.PASSWORD }}
        remote_folder: 'a/'
        local_folder: '.'
        cleanup: false
        include: '[ "*", "**/*" ]'
        exclude: '["node_modules/**", ".git/**", "*.env"]'
        pasive: true
